name: Build and Deploy
on:
  push:
    branches: main
jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1
      
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      
      - name: Install Project Dependencies
        run: npm ci
      
      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@2.12.34
      
      - name: Build
        run: gatsby build
      
      - name: Verify build
        run: ls -la public

      - name: FTP Deployer
        # You may pin to the exact commit or the version.
        # uses: sand4rt/ftp-deployer@b4d8a88f104b46a1bcfac8f69b3413986cc0ce28
        uses: sand4rt/ftp-deployer@v1.3
        with:
          # SFTP on
          sftp: false
          # FTP host URL like: ftp.host.com or sftp.host.com
          host: multiplace.org
          # Ftp username
          username: jondujaka
          # Ftp password
          password: ${{ secrets.FTP_PASSWORD }}
          # The remote folder location of your FTP server
          remote_folder: /front
          # The local folder location
          local_folder: public
